_BASE_: avism_SwinL_IN.yaml
DATASETS:
  TEST: ("avis_test",)
INPUT:
  MIN_SIZE_TEST: 448
MODEL:
  WEIGHTS: "./checkpoints/AVISM_SwinL_IN.pth"
  AVISM:
    AURORA_ENABLED: True
OUTPUT_DIR: "./outputs/avism_SwinL_IN_AURORA"
